package shareables.network.requests;

public enum RequestIdentifier {
    LOG_IN,
    CHANGE_PASSWORD,
    GET_USER,
    CHANGE_EMAIL_ADDRESS,
    CHANGE_PHONE_NUMBER,
    GET_STUDENT_COURSE_DTOS,
    GET_PROFESSOR_COURSE_DTOS,
    GET_DEPARTMENT_COURSE_DTOS,
    GET_ACTIVE_COURSE_DTOS,
    GET_PROFESSOR_DTOS,
    ASK_FOR_DORM,
    ASK_FOR_CERTIFICATE,
    CHANGE_COURSE_NAME,
    CHANGE_COURSE_TEACHING_PROFESSORS,
    CHANGE_COURSE_NUMBER_OF_CREDITS,
    CHANGE_COURSE_LEVEL,
    REMOVE_COURSE,
    ADD_COURSE,

}